### ISSUE TITLE
Perhaps one for XP x64?

### ISSUE THREAD

**Issue by HypixionGaming** [abbodi1406/dotNetXP#1]
Sorry If I did this wrong, but I was curious about a x64 variant of this utility obviously for XP Pro x64 It might come In handy I would do It. But I have no programming knowledge

**Quick Edit i have tested the regular version on xp-64 but all does is instantly complete without installing anything

**Comment by abbodi1406** [comment]
I merely updated the original installer by @ricktendo64
creating new one for XP x64 from the scratch is not easy task, .NET updates are very messy
but i'll see what i can do

**Comment by HypixionGaming** [comment]
Don't worry If It Is too much trouble! It was just an Idea/question

**Comment by abbodi1406** [comment]
Accomplished
