### ISSUE TITLE
Cropped text inside help dialogbox

### ISSUE THREAD

**Issue by spyrosmas** [abbodi1406/dotNetXP#3]
Please make the control box which holds the help text bigger so, all of the help text can be seen, even on higher dpi, other than the default 96dpi. Display Properties->Settings->Advanced->General tab->DPI setting->custom

**Comment by abbodi1406** [comment]
I just used pre-made 7zsfx module, i don't think it's possible to detect dpi

you can always put the mouse cursor inside the box, then press Ctrl+A / Ctrl+C to copy the text

**Comment by spyrosmas** [comment]
I enlarge the text box with Resource Hacker and save the executable. Then I see all of the text. If you willing to change that, there is no need to detect DPI, just made a larger box.
